### ISSUE TITLE
Error building project in Travis environment

### ISSUE THREAD

**Issue by Flibio** [Minecrell/licenser#4]
I get an error running version `0.3` in my Travis environment. More details are available below.

[Travis Build Log](https://travis-ci.org/Flibio/WinterWonderland/builds/173796147)
[GitHub Project](https://github.com/Flibio/WinterWonderland/tree/develop)

**Comment by Minecrell** [comment]
You are building your project with [the installed Gradle version of Travis](https://github.com/Flibio/WinterWonderland/blob/develop/.travis.yml#L8) instead of using the Gradle wrapper. licenser requires a recent Gradle version to run properly, the installed version on Travis is out of date.

You can fix this by changing the line to use the `./gradlew` script.

By the way, [making the Gradle wrapper script executable](https://github.com/Flibio/WinterWonderland/blob/develop/.travis.yml#L6-L7) isn't necessary if you commit it correctly (with executable permissions) to your repo. On Linux you can just do `chmod +x gradlew` locally, for Windows execute `git update-index --chmod=+x gradlew` and commit the changes.

**Comment by Flibio** [comment]
Thank you very much! Everything is working great now.
